Repository alexandr-io/backend, pull requests merged in 2021-11, with the labels that each got.

#128 fix: media deployment
  microservices/media/deployment/preprod/app/PersistantVolume.yaml
  microservices/media/deployment/preprod/app/PersistantVolumeClaim.yaml
  microservices/media/deployment/prod/app/PersistantVolume.yaml
  microservices/media/deployment/prod/app/PersistantVolumeClaim.yaml
Labels: bug

#133 Fix 404 on book and cover download
  microservices/media/app/handlers/cover.go
  microservices/media/app/handlers/download.go
  microservices/media/app/handlers/upload_cover.go
Labels: bug, enhancement

#132 Add payment session route
  microservices/payment/app/data/session.go
  microservices/payment/app/go.sum
  microservices/payment/app/handlers/customer.go
  microservices/payment/app/handlers/subscribe.go
  microservices/payment/app/handlers/subscriptionList.go
  microservices/payment/app/rooting.go
  microservices/payment/app/stripe/customer/read.go
  microservices/payment/app/stripe/session/create.go
Labels: enhancement
